media_automater/urls.py
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from media_automater import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'media_automater.views.home', name='home'),
    # url(r'^media_automater/', include('media_automater.foo.urls')),
    url(r'^home/$', 'media.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    (r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'registration/login.html'}),

    # Dajax
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),



    # Catch all for home
    url(r'^$', 'media.views.home', name='home'),
)

urlpatterns += staticfiles_urlpatterns()

media/models.py
from django.db import models

# Create your models here.

media/forms.py
__author__ = 'djvol_000'

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit


class SearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('search', 'Search', onclick="search_media(); return false;", onsubmit="search_media(); return false;"))
        self.helper.form_id = 'search_form'

    types =[('movie', 'Movie'), ('show', 'TV Show')]
    type = forms.ChoiceField(choices=types, widget=forms.RadioSelect(attrs={'class': 'type_select'}), required=True, label="", initial=types[0][0])
    search_text = forms.CharField(label='Search', required=True)
    optional_season = forms.CharField(label='Season', required=False)
    optional_episode = forms.CharField(label='Episode', required=False)


class TorrentForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(TorrentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('search', 'Search', onclick="search_torrents(); return false;", onsubmit="search_torrents(); return false;"))
        self.helper.form_id = 'torrent_form'

    torrent_search_text = forms.CharField(label='Search Torrents', required=False, help_text="<p><i>ex. World War Z (720p / 1080p)</i></p><p><i>ex. Breaking Bad s01e02 720p</i></p>")

    site_choices = [('Kickass', 'Kickass Torrents'), ('TorrentHound', 'TorrentHound')]

    torrent_search_site = forms.ChoiceField(label='Torrent Site', required=True, help_text='<i>Torrent site to search</i>', choices=site_choices)

media/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import Context, loader
from media.plex_funcs import *
from media.forms import *
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from media_automater.config import TRANSMISSION_DOWNLOAD


@login_required()
def home(request):
    page_title = "media automater"
    media_header_title = "plex media"
    torrent_header_title = "torrent search"
    files_header_title = "torrent management"
    template = loader.get_template('javascript.html')
    content = Context({
	    'page_title': page_title,
	    'media_header_title': media_header_title,
        'torrent_header_title': torrent_header_title,
        'files_header_title': files_header_title,
        'search_form': SearchForm(),
        'torrent_form': TorrentForm(),
        'download_url': TRANSMISSION_DOWNLOAD
	})
    content.update(csrf(request))
    return HttpResponse(template.render(content))

templates/index.html
{% load dajaxice_templatetags %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">
	<title>{{page_title}}</title>
    <link rel="stylesheet" href="/static/css/styles.css" type="text/css">
    <script src="/static/js/jquery-2.0.3.min.js" type="text/javascript"> </script>
    <script src="/static/js/jquery.ba-serializeobject.min.js" type="text/javascript"> </script>
    <script src="/static/js/jquery.tinysort.js" type="text/javascript"> </script>
    <link type='text/css' href='/static/css/bootstrap.css' rel='stylesheet'>
    <link type='text/css' href='/static/css/bootstrap-theme.css' rel='stylesheet'>

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">

    <!-- INCLUDE SITE JAVASCRIPT -->
    {% block javascript %}

    {% endblock %}
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript">
        function purge_downloads() {
            Dajaxice.media.purge_downloads(purge_downloads_callback);
        }
        function load_media() {
            $('#load_media').empty();
            $('#load_media').append("Loading...");
            Dajaxice.media.load_media(load_media_callback);
        }
        $(document).ready(function() {
            load_media();
        });

        function search_media() {
            $('#data_loader').empty();
            $('#data_loader').append("Loading...");
            Dajaxice.media.search_media(search_callback, $('#search_form').serializeObject() );
        }
        function search_torrents() {
            $('#torrent_loader').empty();
            $('#id_torrent_search_text').addClass('input-loading');
            Dajaxice.media.search_torrent(torrent_callback, $('#torrent_form').serializeObject() );
        }
        function files_information() {
            if ($('#files_reloader').html() === 'Show Torrents') {
                $('#files_reloader').html('Hide Torrents');
            }
            else {
                $('#files_reloader').html('Show Torrents');
            }
            $('#files_loader').slideToggle();
        }
        function downloads_information() {
            if ($('#downloads_reloader').html() === 'Show Downloads') {
                $('#downloads_reloader').html('Hide Downloads');
            }
            else {
                $('#downloads_reloader').html('Show Downloads');
            }
            $('#downloads_loader').slideToggle();
        }
    </script>
    {% dajaxice_js_import %}
</head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="function_wrapper" id="current_media_wrapper">

<h1>{{ media_header_title }}</h1>

<!--<button class="btn btn-success" type="button" onclick="load_media(); return false">Load Current Media</button>-->
<div id="load_media" class="loader">

</div>


<div>
    {% crispy search_form %}
    <div id="data_loader" class="loader">

    </div>
</div>

</div>

<div class="function_wrapper" id="torrent_search_wrapper">
    <h1>{{ torrent_header_title }}</h1>
    <div>
        {%  crispy torrent_form %}
        <div id="torrent_loader" class="loader">

        </div>
    </div>
</div>

<div class="function_wrapper" id="finished_files_wrapper">
    <h1>{{ files_header_title }}</h1>
    <div>
        <button class="btn btn-success" type="button"  id="files_reloader" onclick="files_information(); return false;">Show Torrents</button>
        <button class="btn btn-success" type="button"  id="downloads_reloader" onclick="downloads_information(); return false;">Show Downloads</button>
        <div id="files_loader" style="display:none;" class="loader">
            <div id="torrents_active" class="loader panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title" style="float: left;">Active Torrents</h4>
                    <img id="torrents_active_panel_body-collapse-all" src="/static/img/minus-icon.png" style="cursor: pointer; float: right;" onclick="javascript: shrinkAll('torrents_active_panel_body'); return false;">
                    <div style="clear: both"></div>
                </div>
                <div id="torrents_active_panel_body" class="panel-body">

                </div>
            </div>
            <div id="torrents_stopped" class="loader panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title" style="float: left;">Finished Torrents</h4>
                    <img id="torrents_stopped_panel_body-collapse-all" src="/static/img/minus-icon.png" style="cursor: pointer; float: right;" onclick="javascript: shrinkAll('torrents_stopped_panel_body'); return false;">
                    <div style="clear: both"></div>
                </div>
                <div id="torrents_stopped_panel_body" class="panel-body">

                </div>
            </div>
        </div>
        <div id="downloads_loader" style="display:none;" class="loader">
            <div id="downloads_active" class="loader panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title">Active Downloads</h4>
                </div>
                <div id="active_panel_body" class="panel-body">

                </div>
            </div>
            <div id="downloads_stopped" class="loader panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title" style="float: left;">Finished Downloads</h4>
                    <button id="purge-downloads" style="float: right;" class="btn btn-xs btn-danger" type="button" onclick="purge_downloads(); return false">Purge Finished</button>
                    <div style="clear: both;"></div>
                </div>
                <div id="stopped_panel_body" class="panel-body">

                </div>
            </div>
            <div id="downloads_waiting" class="loader panel panel-warning">
                <div class="panel-heading">
                    <h4 class="panel-title">Pending Downloads</h4>
                </div>
                <div id="waiting_panel_body" class="panel-body">

                </div>
            </div>
        </div>
    </div>
</div>


        </div>
      </div>
    </div>

  </body>
</html>